backend:
  name: git-gateway

media_folder: "images/uploads"
site_url: https://lesinfiltrees.fr

collections:
  - name: "pages"
    label: Pages
    files:
    - name: "/"
      label: "Accueil"
      file:  "pages/home.md"
      fields:
        - {label: Texte, name: body, widget: markdown}
